# Application
spring.application.name=ManageSupplierOrders

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/tricolv2_db
spring.datasource.username=postgres
spring.datasource.password=malik
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true


# Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

stock.valuation.method=FIFO
